name: PR to Google Chat

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify-gchat:
    runs-on: ubuntu-latest
    steps:
      - name: List files (debug)
        run: ls -l

      - name: List all files (debug)
        run: ls -lR

      - name: Send PR details to Google Chat
        env:
          GCHAT_WEBHOOK_URL: ${{ secrets.GCHAT_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
        run: |
          pip install requests
          python .github/workflows/send_to_gchat.py
