name: PR to Google Chat

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify-gchat:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar PR para Google Chat
        env:
          GCHAT_WEBHOOK_URL: ${{ secrets.GCHAT_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_STATUS: ${{ github.event.action }}
        run: |
          MESSAGE="{
            \"text\": \"*Novo evento de Pull Request*: \`${PR_STATUS}\`\n\n📌 *Título:* ${PR_TITLE}\n📝 *Descrição:* ${PR_BODY}\n👤 *Autor:* ${PR_AUTHOR}\n🔗 *Link:* ${PR_URL}\"
          }"

          curl -X POST -H 'Content-Type: application/json' \
            -d "${MESSAGE}" \
            "$GCHAT_WEBHOOK_URL"
