name: PR to Google Chat

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  notify-gchat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Enviar PR para Google Chat
        env:
          GCHAT_WEBHOOK_URL: ${{ secrets.GCHAT_WEBHOOK_URL }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_STATUS: ${{ github.event.action }}
        run: |
          pip install requests
          python .github/scripts/send_to_gchat.py
